### ISSUE TITLE
不支持手机滑动

### ISSUE THREAD

**Issue by chongyuan** [yanhaijing/zepto.slider#1]
zepto是针对手机的，感觉手机滑动还是挺必要的；

**Comment by yanhaijing** [comment]
话说我以看不懂当时写的代码了，好久没维护了，不支持滑动，只支持点击

**Comment by yanhaijing** [comment]
建议还是用个成熟的的框架吧 (┬＿┬)

**Comment by chongyuan** [comment]
恩，好的；因为要用到水平自由拖动，所以下载了swiper  https://github.com/nolimits4web/Swiper

**Comment by yanhaijing** [comment]
嗯嗯 加油 吧
